In [1]:
import math
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

In [2]:
vineyard = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/192_vineyard/192_vineyard.tsv.gz", sep="\t")
vineyard.head()

,lugs_1989,lugs_1990,target
0,1.0,5.0,9.5
1,3.0,8.0,17.5
2,3.0,11.0,18.0
3,3.0,9.0,20.0
4,5.0,9.5,20.5


In [4]:
average_yields = np.array(vineyard[["lugs_1989", "lugs_1990"]].mean(axis=1))
average_yields

array([3.  , 5.5 , 7.  , 6.  , 7.25, 6.75, 7.5 , 7.25, 8.25, 7.5 , 8.5 ,
       7.5 , 7.25, 8.  , 8.  , 8.75, 7.75, 9.  , 7.75, 9.5 , 8.  , 9.5 ,
       7.75, 8.5 , 7.5 , 9.75, 8.  , 9.5 , 6.5 , 9.25, 5.5 , 4.75, 5.  ,
       5.  , 4.5 , 6.5 , 4.5 , 6.  , 5.  , 6.  , 5.5 , 5.75, 4.75, 6.25,
       5.5 , 4.  , 3.  , 4.  , 4.25, 3.25, 3.75, 1.25])

In [1]:
import numpy as np

q20 = np.array([[2., 5., -3., 2.0],
                [-2., 1., 3., -2.],
                [4., 1., 0., 16.]], dtype=float)

def rref(A, tol=1e-12):
    A = A.copy().astype(float)
    rows, cols = A.shape
    r = 0
    for c in range(cols):
        # find pivot in column c, starting at row r
        piv = np.argmax(np.abs(A[r:rows, c])) + r
        if r >= rows or abs(A[piv, c]) <= tol:
            continue
        # swap
        if piv != r:
            A[[r, piv]] = A[[piv, r]]
        # normalize pivot row
        A[r] = A[r] / A[r, c]
        # eliminate all other rows
        for i in range(rows):
            if i != r:
                A[i] = A[i] - A[i, c] * A[r]
        r += 1
        if r == rows:
            break
    # clean tiny values to exact zeros
    A[np.abs(A) < tol] = 0.0
    return A

p20 = rref(q20)
print(p20)


[[1. 0. 0. 4.]
 [0. 1. 0. 0.]
 [0. 0. 1. 2.]]
